{
  imports = [
    ./direnv.nix
    ./emacs.nix
    ./firefox.nix
    ./ghostty.nix
    ./git.nix
    ./hyprland.nix
    ./notmuch.nix
    ./packages.nix
    ./ssh.nix
    ./starship.nix
    ./steam.nix
    ./tmux.nix
    ./waybar.nix
    ./wofi.nix
    ./zen-browser.nix
    ./zsh.nix
  ];
}
