# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6fb04275-28e5-497d-829b-216d04a74f3f";
    fsType = "btrfs";
    options = ["subvol=@root"];
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/9af86944-ab7c-4b9c-b1b1-fb714697e775";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6fb04275-28e5-497d-829b-216d04a74f3f";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/6fb04275-28e5-497d-829b-216d04a74f3f";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/6fb04275-28e5-497d-829b-216d04a74f3f";
    fsType = "btrfs";
    options = ["subvol=@persist"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/6fb04275-28e5-497d-829b-216d04a74f3f";
    fsType = "btrfs";
    options = ["subvol=@log"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
